sudo: false
language: go

go:
    - 1.4.2
install:
    - export GOPATH=$GOPATH/src/github.com/pengswift/bgsave
    - cd $GOPATH
    - wget -qO- https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm | bash
    - go install bgsave
before_script:
script:
    - exit 0


